---
- name: install dependencies
  apt:
    name:
      - unzip
      - curl
      # - consul
    state: present
    update_cache: yes

- name: Create Consul directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/consul
    - /opt/consul/data
    - /etc/consul.d

# - name: Download Consul binary
#   get_url:
#     url: https://releases.hashicorp.com/consul/1.21.2/consul_1.21.2_linux_amd64.zip
#     dest: /tmp/consul.zip

- name: Unzip Consul
  unarchive:
    # src: /tmp/consul.zip
    src: /vagrant/consul01/consul_1.21.2_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: "0755"

- name: download Envoy binary from GitHub
  get_url:
    url: https://github.com/envoyproxy/envoy/releases/download/v1.34.1/envoy-1.34.1-linux-x86_64
    dest: /usr/local/bin/envoy
    mode: "0755"

- name: copy consul_client.hcl
  template:
    src: /vagrant/consul01/consul_client.hcl.j2
    dest: /etc/consul.d/consul.hcl
    force: true

- name: set service_name for Consul Envoy Sidecar
  set_fact:
    service_name: "{{ 'postgres' if ansible_hostname == 'db' else 'hotel-service' }}"

- name: copy hotel service definition for Consul
  copy:
    src: "/vagrant/consul01/hotel-service.json"
    dest: "/etc/consul.d/hotel-service.json"
  when: ansible_hostname == "api"

- name: copy postgres service definition for Consul
  copy:
    src: "/vagrant/consul01/postgres.json"
    dest: "/etc/consul.d/postgres.json"
  when: ansible_hostname == "db"

- name: —Åreate systemd service for Consul
  copy:
    dest: /etc/systemd/system/consul.service
    content: |
      [Unit]
      Description=Consul Agent
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: create systemd service for Envoy
  copy:
    dest: /etc/systemd/system/envoy.service
    content: |
      [Unit]
      Description=Consul Envoy Sidecar
      Requires=consul.service
      After=network.target consul.service

      [Service]
      ExecStart=/usr/local/bin/consul connect envoy -sidecar-for {{ service_name }} -ignore-envoy-compatibility
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: reload systemd
  command: systemctl daemon-reload

- name: enable Consul
  systemd:
    name: consul
    enabled: yes
    state: started

- name: enable Envoy
  systemd:
    name: envoy
    enabled: yes
    state: started
